# Generated by Django 2.0.5 on 2018-05-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_org'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click',
            new_name='click_nums',
        ),
    ]
